# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: load_balancer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'load_balancer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13load_balancer.proto\" \n\x0cRiderRequest\x12\x10\n\x08rider_id\x18\x01 \x01(\t\"\"\n\rDriverRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\"*\n\x12ServerListResponse\x12\x14\n\x0cserver_ports\x18\x01 \x03(\t\")\n\x12\x44riverPortResponse\x12\x13\n\x0bserver_port\x18\x01 \x01(\t\"4\n\x11\x44riverExitRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"$\n\x12\x44riverExitResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc8\x01\n\x13LoadBalancerService\x12;\n\x15GetServerPortForRider\x12\r.RiderRequest\x1a\x13.ServerListResponse\x12=\n\x16GetServerPortForDriver\x12\x0e.DriverRequest\x1a\x13.DriverPortResponse\x12\x35\n\nDriverExit\x12\x12.DriverExitRequest\x1a\x13.DriverExitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'load_balancer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RIDERREQUEST']._serialized_start=23
  _globals['_RIDERREQUEST']._serialized_end=55
  _globals['_DRIVERREQUEST']._serialized_start=57
  _globals['_DRIVERREQUEST']._serialized_end=91
  _globals['_SERVERLISTRESPONSE']._serialized_start=93
  _globals['_SERVERLISTRESPONSE']._serialized_end=135
  _globals['_DRIVERPORTRESPONSE']._serialized_start=137
  _globals['_DRIVERPORTRESPONSE']._serialized_end=178
  _globals['_DRIVEREXITREQUEST']._serialized_start=180
  _globals['_DRIVEREXITREQUEST']._serialized_end=232
  _globals['_DRIVEREXITRESPONSE']._serialized_start=234
  _globals['_DRIVEREXITRESPONSE']._serialized_end=270
  _globals['_LOADBALANCERSERVICE']._serialized_start=273
  _globals['_LOADBALANCERSERVICE']._serialized_end=473
# @@protoc_insertion_point(module_scope)
