# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import load_balancer_pb2 as load__balancer__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in load_balancer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoadBalancerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerPortForRider = channel.unary_unary(
                '/LoadBalancerService/GetServerPortForRider',
                request_serializer=load__balancer__pb2.RiderRequest.SerializeToString,
                response_deserializer=load__balancer__pb2.ServerListResponse.FromString,
                _registered_method=True)
        self.GetServerPortForDriver = channel.unary_unary(
                '/LoadBalancerService/GetServerPortForDriver',
                request_serializer=load__balancer__pb2.DriverRequest.SerializeToString,
                response_deserializer=load__balancer__pb2.DriverPortResponse.FromString,
                _registered_method=True)
        self.DriverExit = channel.unary_unary(
                '/LoadBalancerService/DriverExit',
                request_serializer=load__balancer__pb2.DriverExitRequest.SerializeToString,
                response_deserializer=load__balancer__pb2.DriverExitResponse.FromString,
                _registered_method=True)


class LoadBalancerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServerPortForRider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerPortForDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DriverExit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoadBalancerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerPortForRider': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerPortForRider,
                    request_deserializer=load__balancer__pb2.RiderRequest.FromString,
                    response_serializer=load__balancer__pb2.ServerListResponse.SerializeToString,
            ),
            'GetServerPortForDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerPortForDriver,
                    request_deserializer=load__balancer__pb2.DriverRequest.FromString,
                    response_serializer=load__balancer__pb2.DriverPortResponse.SerializeToString,
            ),
            'DriverExit': grpc.unary_unary_rpc_method_handler(
                    servicer.DriverExit,
                    request_deserializer=load__balancer__pb2.DriverExitRequest.FromString,
                    response_serializer=load__balancer__pb2.DriverExitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LoadBalancerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LoadBalancerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoadBalancerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServerPortForRider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LoadBalancerService/GetServerPortForRider',
            load__balancer__pb2.RiderRequest.SerializeToString,
            load__balancer__pb2.ServerListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerPortForDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LoadBalancerService/GetServerPortForDriver',
            load__balancer__pb2.DriverRequest.SerializeToString,
            load__balancer__pb2.DriverPortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DriverExit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LoadBalancerService/DriverExit',
            load__balancer__pb2.DriverExitRequest.SerializeToString,
            load__balancer__pb2.DriverExitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
