# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ride_sharing_pb2 as ride__sharing__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ride_sharing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RideSharingServiceStub(object):
    """The ride-sharing service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestRide = channel.unary_unary(
                '/ride_sharing.RideSharingService/RequestRide',
                request_serializer=ride__sharing__pb2.RideRequest.SerializeToString,
                response_deserializer=ride__sharing__pb2.RideResponse.FromString,
                _registered_method=True)
        self.GetRideStatus = channel.unary_unary(
                '/ride_sharing.RideSharingService/GetRideStatus',
                request_serializer=ride__sharing__pb2.RideStatusRequest.SerializeToString,
                response_deserializer=ride__sharing__pb2.RideStatusResponse.FromString,
                _registered_method=True)
        self.AcceptRide = channel.unary_unary(
                '/ride_sharing.RideSharingService/AcceptRide',
                request_serializer=ride__sharing__pb2.AcceptRideRequest.SerializeToString,
                response_deserializer=ride__sharing__pb2.AcceptRideResponse.FromString,
                _registered_method=True)
        self.RejectRide = channel.unary_unary(
                '/ride_sharing.RideSharingService/RejectRide',
                request_serializer=ride__sharing__pb2.RejectRideRequest.SerializeToString,
                response_deserializer=ride__sharing__pb2.RejectRideResponse.FromString,
                _registered_method=True)
        self.CompleteRide = channel.unary_unary(
                '/ride_sharing.RideSharingService/CompleteRide',
                request_serializer=ride__sharing__pb2.RideCompletionRequest.SerializeToString,
                response_deserializer=ride__sharing__pb2.RideCompletionResponse.FromString,
                _registered_method=True)
        self.GetAssignedRide = channel.unary_unary(
                '/ride_sharing.RideSharingService/GetAssignedRide',
                request_serializer=ride__sharing__pb2.AssignedRideRequest.SerializeToString,
                response_deserializer=ride__sharing__pb2.AssignedRideDetails.FromString,
                _registered_method=True)
        self.RegisterDriver = channel.unary_unary(
                '/ride_sharing.RideSharingService/RegisterDriver',
                request_serializer=ride__sharing__pb2.RegisterDriverRequest.SerializeToString,
                response_deserializer=ride__sharing__pb2.AcceptRideResponse.FromString,
                _registered_method=True)
        self.AssignRide = channel.unary_unary(
                '/ride_sharing.RideSharingService/AssignRide',
                request_serializer=ride__sharing__pb2.AssignRideRequest.SerializeToString,
                response_deserializer=ride__sharing__pb2.AssignRideResponse.FromString,
                _registered_method=True)
        self.UnregisterDriver = channel.unary_unary(
                '/ride_sharing.RideSharingService/UnregisterDriver',
                request_serializer=ride__sharing__pb2.UnregisterDriverRequest.SerializeToString,
                response_deserializer=ride__sharing__pb2.UnregisterDriverResponse.FromString,
                _registered_method=True)


class RideSharingServiceServicer(object):
    """The ride-sharing service definition
    """

    def RequestRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRideStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssignedRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RideSharingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestRide': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRide,
                    request_deserializer=ride__sharing__pb2.RideRequest.FromString,
                    response_serializer=ride__sharing__pb2.RideResponse.SerializeToString,
            ),
            'GetRideStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRideStatus,
                    request_deserializer=ride__sharing__pb2.RideStatusRequest.FromString,
                    response_serializer=ride__sharing__pb2.RideStatusResponse.SerializeToString,
            ),
            'AcceptRide': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptRide,
                    request_deserializer=ride__sharing__pb2.AcceptRideRequest.FromString,
                    response_serializer=ride__sharing__pb2.AcceptRideResponse.SerializeToString,
            ),
            'RejectRide': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectRide,
                    request_deserializer=ride__sharing__pb2.RejectRideRequest.FromString,
                    response_serializer=ride__sharing__pb2.RejectRideResponse.SerializeToString,
            ),
            'CompleteRide': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteRide,
                    request_deserializer=ride__sharing__pb2.RideCompletionRequest.FromString,
                    response_serializer=ride__sharing__pb2.RideCompletionResponse.SerializeToString,
            ),
            'GetAssignedRide': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssignedRide,
                    request_deserializer=ride__sharing__pb2.AssignedRideRequest.FromString,
                    response_serializer=ride__sharing__pb2.AssignedRideDetails.SerializeToString,
            ),
            'RegisterDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDriver,
                    request_deserializer=ride__sharing__pb2.RegisterDriverRequest.FromString,
                    response_serializer=ride__sharing__pb2.AcceptRideResponse.SerializeToString,
            ),
            'AssignRide': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignRide,
                    request_deserializer=ride__sharing__pb2.AssignRideRequest.FromString,
                    response_serializer=ride__sharing__pb2.AssignRideResponse.SerializeToString,
            ),
            'UnregisterDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterDriver,
                    request_deserializer=ride__sharing__pb2.UnregisterDriverRequest.FromString,
                    response_serializer=ride__sharing__pb2.UnregisterDriverResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ride_sharing.RideSharingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ride_sharing.RideSharingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RideSharingService(object):
    """The ride-sharing service definition
    """

    @staticmethod
    def RequestRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ride_sharing.RideSharingService/RequestRide',
            ride__sharing__pb2.RideRequest.SerializeToString,
            ride__sharing__pb2.RideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRideStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ride_sharing.RideSharingService/GetRideStatus',
            ride__sharing__pb2.RideStatusRequest.SerializeToString,
            ride__sharing__pb2.RideStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ride_sharing.RideSharingService/AcceptRide',
            ride__sharing__pb2.AcceptRideRequest.SerializeToString,
            ride__sharing__pb2.AcceptRideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ride_sharing.RideSharingService/RejectRide',
            ride__sharing__pb2.RejectRideRequest.SerializeToString,
            ride__sharing__pb2.RejectRideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ride_sharing.RideSharingService/CompleteRide',
            ride__sharing__pb2.RideCompletionRequest.SerializeToString,
            ride__sharing__pb2.RideCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssignedRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ride_sharing.RideSharingService/GetAssignedRide',
            ride__sharing__pb2.AssignedRideRequest.SerializeToString,
            ride__sharing__pb2.AssignedRideDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ride_sharing.RideSharingService/RegisterDriver',
            ride__sharing__pb2.RegisterDriverRequest.SerializeToString,
            ride__sharing__pb2.AcceptRideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ride_sharing.RideSharingService/AssignRide',
            ride__sharing__pb2.AssignRideRequest.SerializeToString,
            ride__sharing__pb2.AssignRideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ride_sharing.RideSharingService/UnregisterDriver',
            ride__sharing__pb2.UnregisterDriverRequest.SerializeToString,
            ride__sharing__pb2.UnregisterDriverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
